version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - restapi
    ports:
      - '22181:2181'

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - '29092:29092'
      - "9997:9997"
    networks:
      - restapi
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: kafka

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - '8082:8080'
    networks:
      - restapi
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'

  api:
    container_name: api
    build:
      context: .
    ports:
      - '8080:8080'
    depends_on:
      - kafka
    networks:
      - restapi
    environment:
      kafka_topic-name-stats: 'border.statistics'
      kafka_topic-name-detectors: 'traffic.hardware.detectors'


networks:
  restapi: